import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import Header from "@/components/navigation/Header";
import MyProvider from "@/utils/provider/myProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <MyProvider>
        <html lang="en">
          <body className="bg-black">
            <Header />
            <div className="max-w-lg mx-auto">{children}</div>
          </body>
        </html>
      </MyProvider>
    </ClerkProvider>
  );
}
